version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '18:00'
      timezone: 'Europe/Paris'
    open-pull-requests-limit: 10
    assignees:
      - 'vguillou'
    labels:
      - 'npm'
      - 'dependencies'
    allow:
      - dependency-type: 'development'
    versioning-strategy: 'increase'
