version: 2.1

orbs:
  node: circleci/node@4.1
  slack: circleci/slack@4.1
  codecov: codecov/codecov@1.1

definitions:
  const_path_working_directory: &const_path_working_directory /mnt/ramdisk
  const_path_coverage_file: &const_path_coverage_file reports/coverage/lcov.info
  const_tags_regexp: &const_tags_regexp /^v(\d)+\.(\d)+.(\d)+$/
  const_git_documentation_branch: &const_git_documentation_branch gh-pages

  filter_only_for_tags: &filter_only_for_tags
    filters:
      tags:
        only: *const_tags_regexp
      branches:
        ignore: /.*/

  requires_dependencies: &requires_dependencies
    requires:
      - Install_dependencies

  context_slack: &context_slack
    context:
      - slack-integration
  context_slack_npm: &context_slack_npm
    context:
      - slack-integration
      - npm-publishing

  step_attach_workspace: &step_attach_workspace
    attach_workspace:
      at: *const_path_working_directory
  step_slack_notify_fail: &step_slack_notify_fail
    slack/notify:
      event: fail
      template: basic_fail_1
  step_slack_notify_deploy_success: &step_slack_notify_deploy_success
    slack/notify:
      event: pass
      template: success_tagged_deploy_1

  job_defaults: &job_defaults
    executor: node/default
    working_directory: *const_path_working_directory

  workflow_build: &workflow_build
    jobs:
      - Install_dependencies:
          <<: *context_slack
      - Lint:
          <<: *requires_dependencies
          <<: *context_slack
      - Test:
          <<: *requires_dependencies
          <<: *context_slack
      - Upload_test_coverage:
          requires:
            - Test
          <<: *context_slack
      - Scan_for_vulnerabilities:
          <<: *requires_dependencies
          <<: *context_slack
      - Build:
          <<: *requires_dependencies
          <<: *context_slack
      - Generate_docs:
          <<: *requires_dependencies
          <<: *context_slack

  workflow_publish: &workflow_publish
    jobs:
      - Install_dependencies:
          <<: *filter_only_for_tags
          <<: *context_slack
      - Lint:
          <<: *filter_only_for_tags
          <<: *requires_dependencies
          <<: *context_slack
      - Test:
          <<: *filter_only_for_tags
          <<: *requires_dependencies
          <<: *context_slack
      - Upload_test_coverage:
          <<: *filter_only_for_tags
          requires:
            - Test
          <<: *context_slack
      - Scan_for_vulnerabilities:
          <<: *filter_only_for_tags
          <<: *requires_dependencies
          <<: *context_slack
      - Build:
          <<: *filter_only_for_tags
          <<: *requires_dependencies
          <<: *context_slack
      - Generate_docs:
          <<: *filter_only_for_tags
          <<: *requires_dependencies
          <<: *context_slack
      - Deploy_docs:
          <<: *filter_only_for_tags
          requires:
            - Lint
            - Test
            - Scan_for_vulnerabilities
            - Build
            - Generate_docs
          <<: *context_slack
      - Publish_lib:
          <<: *filter_only_for_tags
          requires:
            - Deploy_docs
          <<: *context_slack_npm

jobs:
  Install_dependencies:
    <<: *job_defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: *const_path_working_directory
      - persist_to_workspace:
          root: *const_path_working_directory
          paths:
            - node_modules
      - <<: *step_slack_notify_fail

  Lint:
    <<: *job_defaults
    steps:
      - checkout
      - <<: *step_attach_workspace
      - run:
          name: Lint sources
          command: yarn run ci:lint
      - <<: *step_slack_notify_fail

  Test:
    <<: *job_defaults
    steps:
      - checkout
      - <<: *step_attach_workspace
      - run:
          name: Test
          command: yarn run ci:test
      - persist_to_workspace:
          root: *const_path_working_directory
          paths:
            - *const_path_coverage_file
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - <<: *step_slack_notify_fail

  Upload_test_coverage:
    <<: *job_defaults
    steps:
      - checkout
      - <<: *step_attach_workspace
      - codecov/upload:
          file: *const_path_coverage_file
      - <<: *step_slack_notify_fail

  Scan_for_vulnerabilities:
    <<: *job_defaults
    steps:
      - checkout
      - <<: *step_attach_workspace
      - run:
          name: Scan for vulnerabilities
          command: yarn run ci:scan
      - <<: *step_slack_notify_fail

  Build:
    <<: *job_defaults
    steps:
      - checkout
      - <<: *step_attach_workspace
      - run:
          name: Build
          command: yarn run build
      - persist_to_workspace:
          root: *const_path_working_directory
          paths:
            - lib
      - store_artifacts:
          path: lib
      - <<: *step_slack_notify_fail

  Publish_lib:
    <<: *job_defaults
    steps:
      - checkout
      - <<: *step_attach_workspace
      - run:
          name: Authenticate with registry
          command: |
            echo "registry=https://$NPM_REGISTRY_FQDN/" > ~/.npmrc
            echo "//$NPM_REGISTRY_FQDN/:_authToken=${NPM_REGISTRY_AUTOMATION_TOKEN}" >> ~/.npmrc
      - run:
          name: Publish package
          command: npm publish
      - <<: *step_slack_notify_fail
      - <<: *step_slack_notify_deploy_success

  Generate_docs:
    <<: *job_defaults
    steps:
      - checkout
      - <<: *step_attach_workspace
      - run:
          name: Generate documentation
          command: yarn run docs
      - persist_to_workspace:
          root: *const_path_working_directory
          paths:
            - docs
      - store_artifacts:
          path: docs
      - <<: *step_slack_notify_fail

  Deploy_docs:
    <<: *job_defaults
    steps:
      - checkout
      - <<: *step_attach_workspace
      - run:
          name: Configure git
          command: |
            git config user.email "vgui-ci@fake.email"
            git config user.name "vgui-ci"
      - add_ssh_keys:
          fingerprints:
            - "80:29:55:1f:57:21:ad:33:09:a9:31:04:87:aa:38:13"
      - run:
          name: Create an empty documentation branch if not exist
          command: |
            if git rev-parse --verify origin/$GIT_DOCUMENTATION_BRANCH ; then exit 0 ; fi
            git checkout --orphan $GIT_DOCUMENTATION_BRANCH --track remote/$GIT_DOCUMENTATION_BRANCH
            git rm -rf .
            git commit -m '[skip ci] docs(docs): creating documentation branch' --allow-empty
            git push origin $GIT_DOCUMENTATION_BRANCH
            git checkout $GIT_CURRENT_REVISION
          environment:
            GIT_DOCUMENTATION_BRANCH: *const_git_documentation_branch
            GIT_CURRENT_REVISION: <<pipeline.git.revision>>
      - run:
          name: Deploy documentation
          command: yarn run cd:deploy-docs
      - <<: *step_slack_notify_fail

workflows:
  version: 2

  Push:
    <<: *workflow_build

  Publish:
    <<: *workflow_publish

  #Nightly:
  #  <<: *workflow_build
  #  triggers:
  #    - schedule:
  #        cron: "0 3 * * *"
  #        filters:
  #          branches:
  #            only:
  #              - master
  #              - develop

  Weekly:
    <<: *workflow_build
    triggers:
      - schedule:
          cron: "0 4 * * 0"
          filters:
            branches:
              only:
                - master
                - develop
